# Generated by Django 5.2.8 on 2025-12-02 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('full_name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=120, null=True)),
                ('memory', models.CharField(blank=True, max_length=110, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_regular', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('screen_diagonal', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('value', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='parser_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='parser_app.product')),
            ],
        ),
    ]
